# Generated by Django 5.2.6 on 2026-09-20 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_autor_editorial_categoria_libro_ejemplar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_qr', models.CharField(max_length=500, unique=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carnet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_recogida_limite', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion_pactada', models.DateTimeField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('LISTO', 'Listo para recoger'), ('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto'), ('VENCIDO', 'Vencido'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='catalogo.biblioteca')),
                ('bibliotecario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_gestionados', to=settings.AUTH_USER_MODEL)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='catalogo.ejemplar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='prestamos.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('NOTIFICADA', 'Notificada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=12)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_espera', to='catalogo.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_espera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('usuario', 'libro'), name='unique_active_waiting_list_entry')],
            },
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['usuario'], name='prestamos_p_usuario_89b2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['estado'], name='prestamos_p_estado_ca1dfe_idx'),
        ),
    ]
