# Generated by Django 5.2.6 on 2026-09-20 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveSmallIntegerField(db_column='año')),
                ('tipo_curso', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=100, unique=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_estudiante', to='academics.carrera')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_estudiante', to='academics.facultad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
