# Generated by Django 5.2.6 on 2026-09-20 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('facultad_asociada', models.CharField(blank=True, max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bibliotecas_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
