# Generated by Django 5.2.6 on 2026-09-20 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='catalogo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=500)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('anio_edicion', models.PositiveIntegerField(blank=True, null=True)),
                ('edicion', models.CharField(blank=True, max_length=100)),
                ('resumen', models.TextField(blank=True)),
                ('portada_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('autores', models.ManyToManyField(related_name='libros', to='catalogo.autor')),
                ('categorias', models.ManyToManyField(related_name='libros', to='catalogo.categoria')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='catalogo.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_ejemplar', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('DANADO', 'Dañado'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=12)),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=300)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejemplares', to='catalogo.biblioteca')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejemplares', to='catalogo.libro')),
            ],
            options={
                'indexes': [models.Index(fields=['libro'], name='catalogo_ej_libro_i_83c418_idx')],
            },
        ),
    ]
