# Generated by Django 5.2.6 on 2026-09-20 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('entidad', models.CharField(max_length=200)),
                ('entidad_id', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs_auditoria',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['usuario', 'timestamp'], name='logs_audito_usuario_31a52a_idx'), models.Index(fields=['entidad', 'entidad_id'], name='logs_audito_entidad_4a0511_idx')],
            },
        ),
    ]
